### ISSUE TITLE
accept() on ipv6 socket fails

### ISSUE THREAD

**Issue by dpc** [alexcrichton/net2-rs#30] opened 2016-03-16 05:00 UTC
Originally reported in https://github.com/dpc/mioco/issues/116 . 

I reduced to:

```
#[macro_use]
extern crate log;
extern crate env_logger;
extern crate net2;

use std::{net,str};

const DEFAULT_LISTEN_ADDR : &'static str = "::1";
fn listend_addr() -> net::IpAddr {
    str::FromStr::from_str(DEFAULT_LISTEN_ADDR).unwrap()
}

fn main() {
    env_logger::init().unwrap();
    info!("Starting...");

    let addr = listend_addr();
    let builder = net2::TcpBuilder::new_v6().unwrap();
    builder.only_v6(true).unwrap();
    let addr = net::SocketAddr::new(addr.clone(), 0);
    builder.bind(&addr).unwrap();
    let listener = builder.to_tcp_listener().unwrap();
    info!("Listening on {:?}", listener.local_addr());

    let _ = listener.accept().unwrap();
    info!("Stopped.");
}
```

panicking on `accept().unwrap()` with:

```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 22, message: "Invalid argument" } }', ../src/libcore/result.rs:746
```

with strace reporting:

```
socket(PF_INET6, SOCK_STREAM, IPPROTO_IP) = 3
ioctl(3, FIOCLEX)                       = 0
setsockopt(3, SOL_IPV6, IPV6_V6ONLY, [1], 4) = 0
bind(3, {sa_family=AF_INET6, sin6_port=htons(0), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = 0
futex(0x7f2d749880c8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
accept4(3, 0x7ffcd0e43b20, 0x7ffcd0e43b1c, SOCK_CLOEXEC) = -1 EINVAL (Invalid argument)
```

**Comment by alexcrichton** [comment] 2016-03-16 18:02
In this example it looks like a `listener.listen(..)` is missing? Was that left out by accident from the reproduction?

**Comment by troplin** [comment] 2016-03-16 20:19
I've originally reported this "problem" and I've left `listen()` out by purpose. I thought that the mioco function that I was using would take an unbound `TcpListener`.

So, it's not a problem with net2, but I do wonder what `to_tcp_listener()` is good for...

**Comment by alexcrichton** [comment] 2016-03-16 20:33
That's useful if you're going to perform the `listen` yourself at a later point or something like that, it's basically just included for compatibility.

**Comment by troplin** [comment] 2016-03-16 20:53
But there's no `listen` method neither in `TcpListener`, nor in `TcpListenerExt` that you could call afterwards.

Additionally, I find it a bit confusing that if you just use `std` methods, there's no `listen` call involved at all, just `bind` and then `accept`. OTOH with the `net2` method, a call to `listen` is required.

**Comment by alexcrichton** [comment] 2016-03-16 21:04
Yeah this is when you're calling `listen` specifically from libc itself.

**Comment by alexcrichton** [comment] 2016-07-15 16:07
Closing as I believe this wasn't a bug with net2 itself

**Closed as completed by alexcrichton** 2016-07-15 16:07 UTC
